name: Deploy Astro to Pages

on:
  push:
    branches: ['master']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    env:
      ALGOLIA_API_KEY: ${{ vars.ALGOLIA_API_KEY }}
      ALGOLIA_APP_ID: ${{ vars.ALGOLIA_APP_ID }}
      ALGOLIA_INDEX_NAME: ${{ vars.ALGOLIA_INDEX_NAME }}
      PUBLIC_URL: ${{ vars.PUBLIC_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site output
        uses: withastro/action@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
